FROM tensorflow/serving

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /48_tf_serving
COPY modelo_vehiculo /48_tf_serving/modelo_vehiculo

EXPOSE 8601

ENTRYPOINT tensorflow_model_server \
  --rest_api_port=8601 \
  --model_name=cars_model \
  --model_base_path=/48_tf_serving/modelo_vehiculo
